baseurl: "/"
languageCode: en-us
theme: hugo-theme-terminal
paginate: 5
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  centerTheme: no
  contentTypeName: post
  fullWidthTheme: yes
  showMenuItems: 3
  themeColor: blue
languages:
  en:
    copyright: '© 2021 Naples Park Music'
    keywords: 'guitar, lessons, naples'
    menu:
      main:
        - identifier: about
          name: About
          url: /about
        - identifier: contact
          name: Contact
          url: /contact
        - identifier: lessons
          name: Lessons
          url: /lessons
        - identifier: listen
          name: Listen
          url: /listen
        - identifier: testimonials
          name: Testimonials
          url: /testimonials
    menuMore: Show more
    params:
      logo:
        logoHomeLink: /
        logoText: Naples Park Music
    readMore: Read more
    readOtherPosts: More Information
    subtitle: When you think music...think Naples Park Music!
    title: Naples Park Music
    Description: Guitar store in Naples, FL
